version: '3.1'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecret
      MYSQL_DATABASE: acme
      MYSQL_USER: pangolin
      MYSQL_PASSWORD: VerySecret
    ports:
      - 3306:3306
